active_power <- read.table("household_power_consumption.txt", skip=1, sep = ";")
names(active_power) <- c("Date","Time","Global_active_power", "Global_reactive_power","Voltage","Global_intensity", "Sub_metering_1","Sub_metering_2","Sub_metering_3")
sub_active_power <- subset(active_power, active_power$Date == "1/2/2007" | active_power$Date == "2/2/2007")
date_time <- strptime(paste(sub_active_power$Date, sub_active_power$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
global_active_power <- as.numeric(sub_active_power$Global_active_power)
global_reactive_power <- as.numeric(sub_active_power$Global_reactive_power)
voltage <- as.numeric(sub_active_power$Voltage)
subMetering1 <- as.numeric(sub_active_power$Sub_metering_1)
subMetering2 <- as.numeric(sub_active_power$Sub_metering_2)
subMetering3 <- as.numeric(sub_active_power$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2))
plot(date_time, global_active_power, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(date_time, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(date_time, subMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(date_time, subMetering2, type="l", col="red")
lines(date_time, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(date_time, global_reactive_power, type="l", xlab="datetime", ylab = "Global_reactive_power")
dev.off()