active_power <- read.table("household_power_consumption.txt", skip=1, sep = ";")
names(active_power) <- c("Date","Time","Global_active_power", "Global_reactive_power","Voltage","Global_intensity", "Sub_metering_1","Sub_metering_2","Sub_metering_3")
sub_active_power <- subset(active_power, active_power$Date == "1/2/2007" | active_power$Date == "2/2/2007")
date_time <- strptime(paste(sub_active_power$Date, sub_active_power$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
global_active_power <- as.numeric(sub_active_power$Global_active_power)
subMetering1 <- as.numeric(sub_active_power$Sub_metering_1)
subMetering2 <- as.numeric(sub_active_power$Sub_metering_2)
subMetering3 <- as.numeric(sub_active_power$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(date_time, subMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(date_time, subMetering2, type="l", col="red")
lines(date_time, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()